---
title: "Project Outline"
output: html_notebook
---

## Analysis

- Break data into training and test sets

- Build a few two-stage logistical regression model: propensity to answer, followed by likliehood to purchase a term loan given that the person answers.

- Build a random forest model

- Test the models against each other and pick the best model

- Build a tool to model the distribution of expected purchase outcomes given different target parameters and given a choice of model

- Establish cutoffs for "worth it" (% of called who purchase) and identify which groups are worth targeting given these cutoffs *and* given a minimum sample size (i.e. you can reach out to lower answering groups with higher yield percentages if the sample size is large enough to justify)

## Application

- Build an application that proposes lists of customers to call given cutoffs from the first area, plus inputs related to exogenous factors (CPI, Euribor, etc.)

## LearnR

- Overview of project
- Literature Review
- Justification of Methodology
    - Logistic Regression
    - Random Forest
    - Which works better?
- Implementation in R
- Similar projects


