---
title: "Model Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(dplyr)
```

```{r global, include=FALSE}

predictions <- readRDS("predictions.RDS") %>%
  filter(data == "test") %>%
  mutate(
    logistic_predict = ifelse(logistic_predict_no < .88, "yes", "no")
  ) %>%
  select(-c(data, logistic_predict_no))

```


# Sidebar {.sidebar}

### Inputs

```{r}

sliderInput('calls_per_day', "Calls per Day", min = 100, max = 500, value = 200, step = 50)
sliderInput('samples', "Samples", min = 100, max = 500, value = 250, step = 50)

```


### Filters

```{r}

sliderInput('cons_price_idx', "Consumer Price Index", min(predictions$cons_price_idx), max(predictions$cons_price_idx), value = c(min(predictions$cons_price_idx), max(predictions$cons_price_idx)), step = .2)
```

-------

``` {r}

sliderInput('age', "Age", min(predictions$age), max(predictions$age), value = c(min(predictions$age), max(predictions$age)))
# selectizeInput('job', "Choose Jobs", choices = unique(predictions$job), selected = unique(predictions$job), multiple = TRUE)
selectizeInput('education', "Choose Education", choices = unique(predictions$education), selected = unique(predictions$education), multiple = TRUE)
checkboxGroupInput('cellphone', "Contact Method", choices = unique(predictions$contact), selected = unique(predictions$contact))

```


# Sample


```{r}

universe_of_samples <- reactive({
  
  predictions %>%
    filter(
      cons_price_idx >= min(input$cons_price_idx),
      cons_price_idx <= max(input$cons_price_idx),
      age >= min(input$age),
      age <= max(input$age),
      # job %in% unique(input$job),
      education %in% unique(input$education),
      contact %in% unique(input$cellphone)
    ) %>%
    select(term_deposit, logistic_predict, downsample_predict)
  })


# --



samples <- reactive({
  
  tibble(sample = (1:input$samples)) %>%
    mutate(
      data = map(sample, function(x) universe_of_samples() %>% 
                   sample_n(size = input$calls_per_day, replace = TRUE) %>%
                   summarize(
                     total_calls = nrow(.),
                     actual = sum(ifelse(term_deposit == "yes", 1, 0)),
                     logistic = sum(ifelse(logistic_predict == "yes", 1, 0)),
                     correct_logistic = sum(ifelse(logistic_predict == "yes" & term_deposit == "yes", 1, 0)),
                     random_forest = sum(ifelse(downsample_predict == "yes", 1, 0)),
                     correct_random_forest = sum(ifelse(logistic_predict == "yes" & term_deposit == "yes", 1, 0)),
                     percent_overall = round(actual / total_calls, 2),
                     percent_logistic = round(correct_logistic/logistic, 2),
                     percent_random_forest = round(correct_random_forest/random_forest, 2),
                     logistic_missed = actual - correct_logistic,
                     random_forest_missed = actual - correct_random_forest
                   )
                 )
    ) %>%
    tidyr::unnest(data) %>%
    summarize_all(function(x) str_c(quantile(x), collapse = ", "))

  
})






output$table <- renderTable({

  # class(individuals())
  samples()
  
    })
  


tableOutput("table")


```


